### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by mryuuki0823** [Mi5Devs/android_device_xiaomi_gemini#2]
> Starting build with ninja
> ninja: Entering directory `.'
> ninja: error: '/media/mryuuki0823/Ubuntu/cm14/out/target/product/gemini/obj/KERNEL_OBJ/usr', needed by '/media/mryuuki0823/Ubuntu/cm14/out/target/product/gemini/obj/STATIC_LIBRARIES/libsdcard_intermediates/sdcard.o', missing and no known rule to make it
> build/core/ninja.mk:151: ターゲット 'ninja_wrapper' のレシピで失敗しました
> make: **\* [ninja_wrapper] エラー 1
> make: ディレクトリ '/media/mryuuki0823/Ubuntu/cm14' から出ます

How to solve this?

environment
- Corei7 860
- 12GB RAM
- Ubuntu16.04
- Java 8
- Cyanogenmod 14

**Comment by whyorean** [comment]
The Kernel Target in BoardConfig.mk may not be the same as that of the Kernel Directory.
Also check the defconfig.

TARGET_KERNEL_CONFIG := msm_defconfig
TARGET_KERNEL_SOURCE := kernel/xiaomi/msm8996

**Comment by bgcngm** [comment]
Compilation errors are not up for discussion here. Besides, the device tree is not updated for N builds.
